[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']


[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
hook_add = '''
	let g:deoplete#sources#jedi#python_path = '/usr/local/bin/python3'
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python']
hook_add = '''
	let g:ale_linters = {
		\	'python'	:	['flake8'],
		\	}

	let g:ale_sign_column_always = 1
	let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
	let g:ale_echo_msg_error_str = 'E'
	let g:ale_echo_msg_warning_str = 'W'
	let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'

	let g:ale_lint_on_enter = 1
	let g:ale_lint_on_save = 1
	let g:ale_lint_on_text_change = 'never'

	nnoremap <silent> <C-k> <Plug>(ale_previous_wrap)
	nnoremap <silent> <C-j> <Plug>(ale_next_wrap)
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

