[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
	syntax enable
	set t_Co=256
	autocmd MyAutoCmd VimEnter * nested colorscheme molokai
	autocmd MyAutoCmd ColorScheme * highlight Comment ctermfg=102
	autocmd MyAutoCmd ColorScheme * highlight Visual ctermfg=244
	autocmd MyAutoCmd ColorScheme * highlight Normal ctermbg=none
	autocmd MyAutoCmd ColorScheme * highlight LineNr ctermbg=none
	autocmd MyAutoCmd ColorScheme * highlight SignColumn ctermbg=none
	autocmd MyAutoCmd ColorScheme * highlight VertSplit ctermbg=none
	autocmd MyAutoCmd ColorScheme * highlight NonText ctermbg=none
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
		\'colorscheme'  :'one',
		\'active'   :   {
		\	'left'	:	[	['mode', 'paste'],
		\							['readonly', 'filename', 'modified', 'ale']	]
		\},
		\'component_function'	:	{
		\	'ale'	:	'ALEGetStatusLine'
		\}
		\}
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
	let NERDTreeShowHidden=1
	nnoremap <silent><C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    set completeopt-=preview
'''

[[plugins]]
repo = 'Shougo/neco-vim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
	if dein#util#_is_windows()
		let cmd = 'tools\\update-dll-mingw'
	elseif dein#util#_is_cygwin()
		let cmd = 'make -f make_cygwin.mak'
	elseif executable('gmake')
		let cmd = 'gmake'
	else
		let cmd = 'make'
	endif
		let g:dein#plugin.build = cmd
	'''

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
    let g:neoterm_autoinsert = 1
    let g:neoterm_default_mod = 'belowright'
    nnoremap <silent> <C-e><C-e> :TREPLSendFile<CR>
    nnoremap <silent> <C-e>c :T cd "$(dirname  %)";g++  %;./a.out<CR>
    nnoremap <silent> vt :Ttoggle<CR>
'''

