#!/bin/zsh

if git_status=$(cd $1 && git status 2>/dev/null ); then
  git_branch="$(echo $git_status| awk 'NR==1 {print $2}')"
  case $git_status in
    *Changes\ not\ staged* ) state="#[fg=colour013,bg=black,bold] ~ #[fg=default]" ;;
    *Changes\ to\ be\ committed* ) state="#[fg=blue,bg=black,bold] + #[default]" ;; 
    * ) state="#[fg=green,bg=black] ✔ #[default]" ;;
  esac
  if [[ $git_branch = "master" ]]; then
    git_info="#[bg=black,fg=cyan]⭠ #[default]${state}#[underscore]#[bg=black,fg=cyan]${git_branch}#[default]#[bg=black,fg=cyan] "
  else
    git_info="#[bg=black,fg=colour014]⭠ #[default]${state}#[underscore]#[bg=black,fg=colour014]${git_branch}#[default]#[bg=black,fg=colour014] "
  fi
else
  git_info=""
fi

array=( `echo $1 | tr -s '/' ' '`)
last_index=`expr ${#array[@]}`
current_dir="${array[${last_index}]}"

# current_dir=`get_last_dir $1`
directory="#[bg=black,fg=cyan, bold] [$current_dir]#[default]"

echo "$directory$git_info"
# echo "$current_dir"
